EXP_DIR: tabletop_object
INPUT: RGBD
PIXEL_MEANS: !!python/tuple [102.9801, 115.9465, 122.7717]
## optimizer parameters
OPTIMIZER:
  TRAINABLE: True
  WEIGHT_DECAY: 0.0005
  LEARNING_RATE: 0.00001
  MILESTONES: !!python/tuple [3]
  MOMENTUM: 0.9
  BETA: 0.999
  GAMMA: 0.1
## training parameters
TRAIN:
  IMS_PER_BATCH: 6
  NUM_UNITS: 64
  SNAPSHOT_INFIX: resnet34_8s_embedding_cosine_rgbd_add_sampling
  SNAPSHOT_EPOCHS: 1
  SNAPSHOT_PREFIX: seg
  CHROMATIC: True
  ADD_NOISE: True
  VISUALIZE: False
  FUSION_TYPE: add
  ## embedding training parameters
  EMBEDDING_PRETRAIN: True
  EMBEDDING_SAMPLING: True
  EMBEDDING_SAMPLING_NUM: 1000
  EMBEDDING_NORMALIZATION: True
  EMBEDDING_METRIC: cosine
  EMBEDDING_ALPHA: 0.02
  EMBEDDING_DELTA: 0.5
  EMBEDDING_LAMBDA_INTRA: 10.0
  EMBEDDING_LAMBDA_INTER: 10.0
TEST:
  SINGLE_FRAME: True
  HOUGH_LABEL_THRESHOLD: 400
  HOUGH_VOTING_THRESHOLD: 10
  IMS_PER_BATCH: 1
  HOUGH_SKIP_PIXELS: 10
  DET_THRESHOLD: 0.1
  SCALES_BASE: !!python/tuple [1.0]
  VISUALIZE: True
  SYNTHESIZE: True
  POSE_REFINE: False
  ROS_CAMERA: D415
